Update ios1.yml

diff --git a/.github/workflows/ios1.yml b/.github/workflows/ios1.yml
--- a/.github/workflows/ios1.yml
+++ b/.github/workflows/ios1.yml
@@ -41,7 +41,7 @@ jobs:
           scheme: ${{ 'default' }}
           platform: ${{ 'iOS Simulator' }}
         run: |
-          npx react-native run-ios --simulator="iPhone 12"
+          npx react-native run-ios --simulator="iPhone 12" || (echo "Failed to build iOS project. Attempting Xcode build logs capture..." && xcodebuild -showBuildLog -project "myapp.xcodeproj")
           cd ios
           device=`xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//"`
           if [ $scheme = default ]; then scheme=$(cat default); fi
